### ISSUE TITLE
INTERNAL_SERVICE_ERROR

### ISSUE THREAD

**Issue by tony0121** [paypal/PayPal-iOS-SDK#244]
Hi there,
When I use an live account (no link any credit card) to login PP, it always got an internal error：
PayPal SDK: Request has failed with error: INTERNAL_SERVICE_ERROR - System error. Please try again later. (500) | PayPal Debug-ID: e6b8fbe522524 [live, PayPal iOS SDK 2.8.1]

![capture](https://cloud.githubusercontent.com/assets/8613552/5700255/f64962f8-9a75-11e4-81b8-cabc0e7329d9.PNG)

It's quite confuse, the alert shows there was a problem communicating with the PayPal servers. Why not alert 'Please check your account' or some words like that?

**Comment by mattjacunski** [comment]
@tony0121 - There is a server issue currently causing 500s to be returned instead of a 422 with a specific error.  The logs for this specific call indicate that the payer account does not have a valid funding source available.  This should be resolved on the server soon (tomorrow).  Sorry for the inconvenience.

**Comment by tony0121** [comment]
Thank you for your prompt reply. I'll take some testing tmr.

**Comment by tony0121** [comment]
I still confuse about the alert. Although the back end log changes to error 422, as follow:
PayPal SDK: Request has failed with error: PAYMENT_CREATION_ERROR - There was a problem setting up this payment. Please visit the PayPal website to check your account. (422) | PayPal Debug-ID: b620e0ad55909 [live, PayPal iOS SDK 2.8.1]
But the alert still shows 'there was a problem communicating with the PayPal servers, Please try again'.
Why not using the words that indicate in the log 'There was a problem setting up this payment. Please visit the PayPal website to check your account' ?

**Comment by romk1n** [comment]
@tony0121 the fix for the error message is coming. stay tuned.

**Comment by ppkai** [comment]
@romk1n does merchant need to update their app to SDK of next version (2.8.2?) to fix this problem? If so, is there an approximate date for the release ?

**Comment by dgoldman-ebay** [comment]
Version 2.8.2, which includes this fix, has now been [released](https://github.com/paypal/PayPal-iOS-SDK/releases).

**Comment by ppkai** [comment]
@dgoldman-ebay thanks for your update :) Here is another concern that merchant's app is based on iOS mSDK ver 2.3.2 and does not support Xcode 6 . Will we create a branch for this issue ?

**Comment by dgoldman-ebay** [comment]
@ppkai We do not create branches of outdated versions of the PayPal-iOS-SDK. We expect our developers to use the latest version of the SDK if they wish to keep up with all fixes and improvements.

I don't know of any major reasons to stick with Xcode 5 these days. Are you sure the merchant's app cannot be built with Xcode 6?

**Comment by ppkai** [comment]
@dgoldman-ebay I'm not clear about why he insists on Xcode5... Will confirm and persuade him :) Thanks again for your prompt reply!

**Comment by patelvishal** [comment]
I m using 2.12.9, and still gets the same error. Any solution ?

**Comment by bluk** [comment]
@patelvishal Can you open a new issue and give the same information like the PayPal Debug-ID? This will help narrow down the possible error. Thanks.

**Comment by komalrathod1190** [comment]
hello,
i have developed 1 android app, which have paypal integrated. i have used 2.9 version.

please help me.

**Comment by bluk** [comment]
@komalrathod1190 Can you open a new issue with details like a PayPal-Debug-ID and what is wrong? Also, can you try using the latest version of the SDK? There were many fixes since 2.9 for iOS 9.

**Comment by Zhandongdu** [comment]
![screenshot_2016-05-28-22-22-36](https://cloud.githubusercontent.com/assets/19629412/15630942/3b9c1f82-2583-11e6-843a-e0653c02f96d.png)
Hi there.
I have faced similar issue.
I dont know the what is the problem.
If you can, please help me.

**Comment by Zhandongdu** [comment]
My error like this.
05-29 09:59:26.471 23185-23845/com.puma.chateaued E/paypal.sdk: request failure with http statusCode:422,exception:Unprocessable Entity
05-29 09:59:26.471 23185-23845/com.puma.chateaued E/paypal.sdk: request failed with server response:{"name":"PAYMENT_CREATION_ERROR","debug_id":"69ffb54d9654a","message":"checkout-session not created","information_link":"https://developer.paypal.com/docs/api/#PAYMENT_CREATION_ERROR"}
05-29 09:59:26.471 23185-23185/com.puma.chateaued E/paypal.sdk: PAYMENT_CREATION_ERROR

**Comment by vaidehimeworld** [comment]
Hi,

I am also getting the same issue. "we're sorry there was a problem setting up this payment. please visit the paypal website to check your account paypal", need help.

**Comment by xiaoleih41** [comment]
This error is not a technical error. It normally has something to do with account setting, country policy or currency policy for a specific type of account. It looks like the payment currency is not supported by the receiver's country account for some reason.  As it's a public forum and it's live account issue, please contact customer service or www.paypal-techsupport.com if you have any further questions.

**Comment by vaidehimeworld** [comment]
how to overcome from this?. what are the steps to follow?

**Comment by xiaoleih41** [comment]
From the look of it, just do not send the payment in the currency that country paypal account doesn't accept. Each region has it's own specific agreement with PayPal. You may contact your regional customer service for more information.
