### ISSUE TITLE
INTERNAL_SERVICE_ERROR

### ISSUE THREAD

**Issue by MichaelEckl** [paypal/PayPal-iOS-SDK#355]
Hi,

i changed my Environment to PayPalEnvironmentSandbox but when i try to log in i get the error below:

PayPal SDK: Request has failed with error: INTERNAL_SERVICE_ERROR - System error. Please try again later. (500) | PayPal Debug-ID: eb3817a89e9d7 [sandbox, PayPal iOS SDK 2.12.3]

Thank you for help,
Michael

**Comment by jaypatel512** [comment]
We are currently facing issues with sandbox returning 500 Exceptions on valid requests. Please hold on to your testing till we get the issue resolved. I will update the ticket here, as soon as it gets fixed.

**Comment by nicomollet** [comment]
Still facing the issues 6 hours later.

Easy to check with the PHP SDK sample app:
http://paypal-php-sdk.herokuapp.com/payments/CreatePaymentUsingPayPal.php

**Comment by MichaelEckl** [comment]
Now i can Login but i get this error:

PAYMENT_CREATION_ERROR - Bei der Verarbeitung der Zahlung ist ein Problem aufgetreten. Loggen Sie sich über die PayPal-Website ein und überprüfen Sie Ihr Konto. (422) | PayPal Debug-ID: 77d45bb5c6900 [sandbox, PayPal iOS SDK 2.12.3]

**Comment by tomwhipple** [comment]
Sandbox is experiencing problems at the moment. We are investigating & will update here when we know more.

**Comment by tomwhipple** [comment]
Sandbox has been restored to service.

**Comment by MichaelEckl** [comment]
Now i can log in and pay, but not process the payment: 
PAYER_ACTION_REQUIRED - System error (PAYER_ACTION_REQUIRED). Please try again later. (400) | PayPal Debug-ID: 25d0b3cb2254a [sandbox, PayPal iOS SDK 2.12.3]

**Comment by bluk** [comment]
@MichaelEckl Please see issue #353 for status updates for that error.

**Comment by MichaelEckl** [comment]
Now it is finally processed and i can see the payment in my sandbox account, but the payment status is no completed it is the checking status. Do i have to set the status to completed or does Paypal that for me?

**Comment by tomwhipple** [comment]
@MichaelEckl payment status is set by the PayPal backend.

**Comment by daisyramos317** [comment]
I've also received this error on version 2.11.3

 PayPal SDK: Request has failed with error: INTERNAL_SERVICE_ERROR - System error. Please try again later. (500) | PayPal Debug-ID: 6b4b5cbe7d98f [sandbox, PayPal iOS SDK 2.11.3]

**Comment by bluk** [comment]
@daisyramos317 There was an issue with sandbox earlier. It should be resolved now.

**Comment by daisyramos317** [comment]
Thanks it's resolved on my end

**Comment by KartikSinghBhadoriya** [comment]
I am facing same issue before 2 hours it's working and now I switch live to sandbox it's give me this error 

PayPal SDK: Request has failed with error: INTERNAL_SERVICE_ERROR - System error. Please try again later. (500) | PayPal Debug-ID: 39c25d213574c, 39c25d213574c [sandbox, PayPal iOS SDK 2.14.2]

Please Help me ASAP

**Comment by 34tm4n** [comment]
I am also facing this same issue in sandbox environment from last 2 days and not fixed yet.

PayPal SDK: Request has failed with error: INTERNAL_SERVICE_ERROR - System error. Please try again later. (500) | PayPal Debug-ID: 3c717589d88c5, 3c717589d88c5 [sandbox, PayPal iOS SDK 2.14.2]

Please help me with it.

**Comment by bluk** [comment]
@KartikSinghBhadoriya @34tm4n Let's use https://github.com/paypal/PayPal-iOS-SDK/issues/440 to track this current 500 issue.

If you require specific support, please open a ticket with [Merchant Technical Support](https://www.paypal-techsupport.com) who can directly communicate with you.

**Comment by kaderkayten** [comment]
I am getting this issue.Any help or improvement?

2016-08-17 15:07:01.961 UnitedTaxi-Passenger[407:133831] PayPal SDK: Request has failed with error: INTERNAL_SERVICE_ERROR - System error. Please try again later. (500) | PayPal Debug-ID: 31143fe659cf, 31143fe659cf [sandbox, PayPal iOS SDK 2.14.5]

**Comment by anuragbhai** [comment]
any updates on this issue?

**Comment by bluk** [comment]
@anuragbhai The Internal Server error is a generic error. If you are encountering this error, please create a new issue. If you are encountering this issue on live production, please open a ticket with [Merchant Technical Support](https://www.paypal-techsupport.com).
